target("echo-server")
    set_kind("binary")
    set_group("example")
    add_files("echo_server.cpp")
    add_includedirs("$(projectdir)/include")
    add_deps("coro")
    add_packages("boost")


target("http-client")
    set_kind("binary")
    set_group("example")
    add_files("http_client.cpp")
    add_includedirs("$(projectdir)/include")
    add_deps("coro")
    add_packages("boost")

target("http-server")
    set_kind("binary")
    set_group("example")
    add_files("http_server.cpp")
    add_includedirs("$(projectdir)/include")
    add_deps("coro")
    add_packages("boost")

target("redis-client")
    set_kind("binary")
    set_group("example")
    add_files("redis_client.cpp")
    add_includedirs("$(projectdir)/include")
    add_deps("coro")
    add_packages("boost")
